services:
  mysql:
    image: mysql:8.0
    container_name: mysql-multi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - internal-net
    expose:
      - "3306"
    volumes:
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    command: --default-authentication-plugin=mysql_native_password


networks:
  internal-net:
    external: true

